name: fe-n8n
channels:
  - defaults
  - conda-forge
dependencies:
  - blinker=1.9.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - expat=2.7.1
  - flask=3.1.0
  - idna=3.7
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - markupsafe=3.0.2
  - openssl=3.0.16
  - pip=25.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dotenv=1.1.0
  - python_abi=3.13
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
