name: fe-n8n
channels:
  - conda-forge
dependencies:
  # Python Version
  - python=3.13

  # --- Celery and its critical, version-sensitive dependencies ---
  # Pinning these versions to prevent the 'vine.five' ModuleNotFoundError.
  # These versions are taken from your working Windows environment.
  - celery=5.3.4
  - vine=5.1.0
  - kombu=5.5.4
  - billiard=4.2.1
  - redis-py  # Use the modern redis client from conda-forge

  # --- Other Core Application Packages ---
  # These are less version-sensitive, so we can be flexible.
  - flask=3.1.0
  - flask-socketio
  - boto3
  - requests
  - pydantic=2.10.3
  - pyyaml
  - python-dotenv
  - gitpython

  # Pip for any non-conda packages
  - pip